Vagrant.configure("2") do |config|
  config.vm.box = "trusty64"
  config.vm.box_url = "http://files.vagrantup.com/trusty64.box"
  
  config.vm.provision :shell, :privileged => false, :path => "bootstrap.sh",run: "always"

  config.vm.network :forwarded_port, guest: 8888, host: 8888
  config.vm.network :forwarded_port, guest: 9000, host: 9000
  config.vm.network :forwarded_port, guest: 9200, host: 9200
  config.vm.network :forwarded_port, guest: 9999, host: 9999

  config.vm.synced_folder "../../letsplay", "/letsplay"
end